### PR TITLE
Fix singleton usages with explicit template instantiation

### PR DESCRIPTION
**Pull request by huangminghuang**

### CODE REVIEW

**Comment by jwillemsen** [comment]
Fuzz fails with "Error: ./connectors/dds4ccm/impl/DomainParticipantManager.cpp:287: found trailing whitespace"

**Comment by mitza-oci** [comment]
Snap CI doesn't appear to be configured correctly and I'm not sure how to fix it.
> $ git clone --depth 1 git://github.com/DOCGroup/MPC.git
> fatal: destination path 'MPC' already exists and is not an empty directory.

Johnny, would you please address this?  Meanwhile I think we can merge this PR based on the Travis and AppVeyor results.

**Comment by jwillemsen** [comment]
@mitza-oci Yes, looks ok to merge, I will have a look again at SnapCI, the build it runs on master does it correctly, not sure why pull request are behaving differently

**Comment by mitza-oci** [comment]
When building master it does
> git clone --depth 1 git://github.com/DOCGroup/MPC.git MPCgit

since the directory name conflicts with $CIAO_ROOT/MPC.  However this is not working with PRs.

**Comment by jwillemsen** [comment]
Yes, I used a special MPC directory for snap, will work next month on some more CIAO changes, will try to solve this at that moment

**Pull request merged**
