### PR TITLE
dds4ccm: if configured to use OpenDDS, inherit from OpenDDS base project in order to get tao_idl flags

### PR DESCRIPTION
**Pull request by mitza-oci**

### CODE REVIEW

**Comment by mitza-oci** [comment]
@jwillemsen something is broken with AppVeyor and vcpkg caching

**Comment by jwillemsen** [comment]
@mitza-oci Try to restart the failing builds today and see what happens

**Comment by jwillemsen** [comment]
@mitza-oci AppVeyor issue has been resolved

**Comment by mitza-oci** [comment]
Looks like it's just a timeout error now on one of the two AppVeyor builds.

**Comment by jwillemsen** [comment]
With azure we have already windows coverage, maybe just remove the appveyor usage?

**Comment by mitza-oci** [comment]
> With azure we have already windows coverage, maybe just remove the appveyor usage?

I have no problem with that.

**Comment by jwillemsen** [comment]
I have removed the appveyor integration, with vcpkg update added the build just takes too long

**Pull request merged**
